name: Chelsea Patricia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc6d2'
    - '#000000'
    - '#1f528b'
    - '#ed00c0'
    - '#e966d3'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
